name: bailey
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+21

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_smart_dialog: ^4.9.7+8
  flutter_svg: ^2.0.10+1
  http: ^1.2.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_switch: ^0.3.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  camera: ^0.11.0+1
  image: ^4.2.0
  cunning_document_scanner: ^1.2.3
  flutter_masonry_view: ^0.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  event_bus: ^2.0.0
  cached_network_image: ^3.3.1
  firebase_messaging: ^14.7.19
  url_launcher: ^6.3.0
  adaptive_dialog: ^2.1.0
  flutter_dotenv: ^5.1.0
  convert: ^3.1.1
  mime: ^1.0.5
  path: ^1.9.0
  path_provider: ^2.1.5
  http_parser: any
  uuid: ^4.4.2
  local_rembg:
    git:
      url: https://github.com/Moasfar-Javed/local_rembg.git
  share: ^2.0.4
  photo_view: ^0.15.0
  native_image_cropper: ^0.6.0
  pinput: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env
  fonts:
    - family: HelveticaNowDisplay
      fonts:
        - asset: fonts/HelveticaNowDisplay-Hairline.ttf
          weight: 100
        - asset: fonts/HelveticaNowDisplay-HairlineI.ttf
          weight: 100
          style: italic
        - asset: fonts/HelveticaNowDisplay-Thin.ttf
          weight: 200
        - asset: fonts/HelveticaNowDisplay-ThinIta.ttf
          weight: 200
          style: italic
        - asset: fonts/HelveticaNowDisplay-ExtLt.ttf
          weight: 300
        - asset: fonts/HelveticaNowDisplay-ExtLtIta.ttf
          weight: 300
          style: italic
        - asset: fonts/HelveticaNowDisplay-Light.ttf
          weight: 300
        - asset: fonts/HelveticaNowDisplay-LightIta.ttf
          weight: 300
          style: italic
        - asset: fonts/HelveticaNowDisplay-Regular.ttf
          weight: 400
        - asset: fonts/HelveticaNowDisplay-RegIta.ttf
          weight: 400
          style: italic
        - asset: fonts/HelveticaNowDisplay-Medium.ttf
          weight: 500
        - asset: fonts/HelveticaNowDisplay-MedIta.ttf
          weight: 500
          style: italic
        - asset: fonts/HelveticaNowDisplay-Bold.ttf
          weight: 700
        - asset: fonts/HelveticaNowDisplay-BoldIta.ttf
          weight: 700
          style: italic
        - asset: fonts/HelveticaNowDisplay-ExtraBold.ttf
          weight: 800
        - asset: fonts/HelveticaNowDisplay-ExtBdIta.ttf
          weight: 800
          style: italic
        - asset: fonts/HelveticaNowDisplay-ExtBlk.ttf
          weight: 900
        - asset: fonts/HelveticaNowDisplay-ExtBlkIta.ttf
          weight: 900
          style: italic
        - asset: fonts/HelveticaNowDisplay-Black.ttf
          weight: 900
        - asset: fonts/HelveticaNowDisplay-BlackIta.ttf
          weight: 900
          style: italic
  